name: dap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - altair
  - bs4
  - fiona
  - gdal
  - geopandas
  - ipykernel
  - jupyter
  - matplotlib
  - pandas
  - plotnine
  - pyogrio
  - scikit-learn
  - seaborn
  - shapely
  - spacy
  - statsmodels
  - vega_datasets
  - streamlit
  - pip
  - lxml
  - pip:
      - vl-convert-python
prefix: /Users/maggieshi/miniconda3/envs/dap

